[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_investment_contract = "EWzksjtUD8Ew1BQZg9LCYK4TEucLLFrrzBreqf681zBb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/brgndy25/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
